# Generated by Django 2.0.2 on 2018-02-13 02:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('djangocms_teaser', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teaser',
            name='cmsplugin_ptr',
            field=models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='djangocms_teaser_teaser', serialize=False, to='cms.CMSPlugin'),
        ),
        migrations.AlterField(
            model_name='teaser',
            name='page_link',
            field=models.ForeignKey(blank=True, help_text='If present image will be clickable', limit_choices_to={'publisher_is_draft': True}, null=True, on_delete=django.db.models.deletion.CASCADE, to='cms.Page', verbose_name='page'),
        ),
    ]
